language: cpp
# sudo: false

addons:
  apt:
    sources:
    packages:
    - swig
    - python-dev
    - python-numpy
    - guile-2.0-dev
    - octave3.2-headers
    - cmake

install:
  - sudo apt-get -qq install guile-2.0-dev octave3.2-headers

script:
  - ./autogen.sh --no-configure
  - mkdir build && pushd build
  - ../configure --prefix=$HOME/.local --enable-shared --enable-maintainer-mode --with-cxx --without-guile
  - make -j2
  - make install
  - python ../test/test_std.py
  - rm -rf * ~/.local
  - cmake -DCMAKE_INSTALL_PREFIX=~/.local -DBUILD_SHARED_LIBS=ON -DWITH_CXX=ON ..
  - make install -j2
  - make tests -j2
  - ctest -j2 --output-on-failure
